sudo: false
language: java
jdk:
  - openjdk7
  - oraclejdk8
env:
  - SPRING_VERSION=3.0.7.RELEASE
  - SPRING_VERSION=3.2.16.RELEASE
  - SPRING_VERSION=4.1.9.RELEASE
  - SPRING_VERSION=4.2.4.RELEASE

# Cache local Maven repository.
cache:
  directories:
    - $HOME/.m2

install:
  - "mvn install -Dspring.version=$SPRING_VERSION -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script:
  - "mvn verify -Dspring.version=$SPRING_VERSION -B"
after_success:
  - mvn jacoco:report coveralls:report
